{
 "title": "Pegasus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name" }
  ]
 },
 "panels": [
  {
   "title": "Pegasus SysAdmin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "各节点内存使用率（百分比）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "集群Load-Balance状态（待执行的balance操作数、已执行的balance操作数等）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "meta_eon_greedy_balancer_balance_operation_count{cluster='$cluster_name', pegasus_job='meta'}",
       "legendFormat": "balance_operation_count"
      },
      {
       "expr": "meta_eon_greedy_balancer_recent_balance_move_primary_count{cluster='$cluster_name', pegasus_job='meta'}",
       "legendFormat": "balance_move_primary_count"
      },
      {
       "expr": "meta_eon_greedy_balancer_recent_balance_copy_primary_count{cluster='$cluster_name', pegasus_job='meta'}",
       "legendFormat": "balance_copy_primary_count"
      },
      {
       "expr": "meta_eon_greedy_balancer_recent_balance_copy_secondary_count{cluster='$cluster_name', pegasus_job='meta'}",
       "legendFormat": "balance_copy_secondary_count"
      }
     ]
    },
    {
     "title": "各ReplicaServer内存用量（单位：MB）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_server_memused_res_MB_{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点存储使用率（百分比）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd2\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd2\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd3\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd3\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd4\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd4\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd5\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd5\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd6\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd6\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd7\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd7\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd8\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd8\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd9\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd9\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd10\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd10\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd11\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd11\"} * 100"
      },
      {
       "expr": "100 - node_filesystem_free_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd12\"} / node_filesystem_size_bytes{fstype = \"ext4\", mountpoint = \"/home/work/ssd12\"} * 100"
      }
     ]
    },
    {
     "title": "P99 Prepare发送端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_PREPARE_ACK_latency_client_ns_{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 Prepare发送端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_PREPARE_ACK_latency_client_ns__p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 Prepare服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_PREPARE_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 Prepare服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_PREPARE_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点Commit QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_stub_replicas_commit_qps{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点Replica个数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_stub_replica_Count_{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点SharedLog最近写入字节数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_stub_shared_log_recent_write_size{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点SharedLog大小（单位：MB）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_stub_shared_log_size_MB_{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "Network In Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_network_receive_bytes_total{device != \"lo\"}[5m]))"
      }
     ]
    },
    {
     "title": "Network Out Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{device != \"lo\"}[5m]))\n"
      }
     ]
    },
    {
     "title": "Network Dropped",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{device != \"lo\"}[5m]) + irate(node_network_transmit_drop_total{device != \"lo\"}[5m])",
       "legendFormat": "{device=\"{{device}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "SSD Await",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total[5m]) / irate(node_disk_reads_completed_total[5m]) + irate(node_disk_write_time_seconds_total[5m]) / irate(node_disk_writes_completed_total[5m])",
       "legendFormat": "{device=\"{{device}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "各节点磁盘读吞吐",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[5m])",
       "legendFormat": "{device=\"{{device}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "各节点磁盘写吞吐",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total[5m])\n",
       "legendFormat": "{device=\"{{device}}\", instance=\"{{instance}}\"}"
      }
     ]
    },
    {
     "title": "各节点最近Flush次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_app_pegasus_recent_flush_completed_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点最近Compaction次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_app_pegasus_recent_compaction_completed_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 单条读排队时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_GET_queue_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 单条读执行时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_GET_exec_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 多条读排队时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_GET_queue_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 多条读执行时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_GET_exec_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 单条写排队时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_PUT_queue_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 单条写执行时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_PUT_exec_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 多条写排队时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_PUT_queue_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 多条写执行时间（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_PUT_exec_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各表RocksDB缓存命中率（统计各表的RocksDB Block Cache命中率；单位：百分比*10000；1M表示100%）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_rdb_block_cache_hit_rate{cluster=\"$cluster_name\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "各节点最近读写失败次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_stub_recent_read_fail_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "read_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_recent_write_fail_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "recent_write_fail_count@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点最近Emergency Checkpoint触发次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_stub_recent_trigger_emergency_checkpoint_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点 P99 RPC报文长度",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_PUT_size_request_server{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "put_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_PUT_size_request_server{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "multi_put_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_GET_size_response_server{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "get_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_GET_size_response_server{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "multi_get_size@{{host_name}}:{{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pegasus Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "单表吞吐 (1RCU=4KB, 1WCU=4KB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_recent_write_cu{cluster=\"$cluster_name\"}",
       "legendFormat": "write_cu@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_recent_write_cu{cluster=\"$cluster_name\"}",
       "legendFormat": "read_cu@{{app}}"
      }
     ]
    },
    {
     "title": "单表QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_get_qps{cluster='$cluster_name'}",
       "legendFormat": "get_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_multi_get_qps{cluster='$cluster_name'}",
       "legendFormat": "multi_get_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_put_qps{cluster='$cluster_name'}",
       "legendFormat": "put_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_multi_put_qps{cluster='$cluster_name'}",
       "legendFormat": "multi_put_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_remove_qps{cluster='$cluster_name'}",
       "legendFormat": "remove_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_multi_remove_qps{cluster='$cluster_name'}",
       "legendFormat": "multi_remove_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_incr_qps{cluster='$cluster_name'}",
       "legendFormat": "incr_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_check_and_set_qps{cluster='$cluster_name'}",
       "legendFormat": "check_and_set_qps@{{app}}"
      },
      {
       "expr": "collector_app_pegasus_app_stat_scan_qps{cluster='$cluster_name'}",
       "legendFormat": "scan_qps@{{app}}"
      }
     ]
    },
    {
     "title": "P99 表级Get服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_GET_latency_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 表级Get服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_GET_latency_ns_p999{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 表级Set服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_PUT_latency_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 表级Set服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_PUT_latency_ns_p999{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 表级MultiGet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_MULTI_GET_latency_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 表级Get服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_MULTI_GET_latency_ns_p999{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 表级MultiSet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_MULTI_PUT_latency_ns_{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 表级MultiSet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_table_level_RPC_RRDB_RRDB_MULTI_PUT_latency_ns_p999{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{app}}@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "异常查询条数（统计各表最近10秒执行时间超过100毫秒的查询条数）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_recent_abnormal_count{cluster=\"$cluster_name\", pegasus_job=\"collector\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Reject数据条数（统计各表最近10秒write throttling reject的数据条数）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_recent_write_throttling_reject_count{cluster=\"$cluster_name\",pegasus_job=\"collector\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Delay数据条数（统计各表最近10秒write throttling delay的数据条数）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_recent_write_throttling_delay_count{cluster=\"$cluster_name\", pegasus_job=\"collector\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Expire数据条数（统计各表最近10秒查询的过期数据条数）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_recent_expire_count{cluster=\"$cluster_name\", pegasus_job=\"collector\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "各表存储用量（统计各表的单备份数据存储用量；单位：MB）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_storage_mb{cluster=\"$cluster_name\", pegasus_job=\"collector\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Filter数据条数（统计各表最近10秒过滤的数据条数）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_recent_filter_count{cluster=\"$cluster_name\", pegasus_job=\"collector\"}",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pegasus Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "集群可用度(单位：百分比*10000; 1M表示100%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_cluster_available_minute{cluster=\"$cluster_name\"}",
       "legendFormat": "cluster_available_minute"
      }
     ]
    },
    {
     "title": "各操作总QPS（统计get、multi_get、put、multi_put、remove、multi_remove、scan各操作的总QPS）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_get_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "get_qps"
      },
      {
       "expr": "collector_app_pegasus_app_stat_multi_get_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "multi_get_qps"
      },
      {
       "expr": "collector_app_pegasus_app_stat_put_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "put_qps"
      },
      {
       "expr": "collector_app_pegasus_app_stat_multi_put_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "multi_put_qps"
      },
      {
       "expr": "collector_app_pegasus_app_stat_remove_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "remove_qpes"
      },
      {
       "expr": "collector_app_pegasus_app_stat_multi_remove_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "multi_remove_qps"
      },
      {
       "expr": "collector_app_pegasus_app_stat_incr_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "incr_qps"
      },
      {
       "expr": "collector_app_pegasus_app_stat_check_and_set_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "check_and_set_qps"
      },
      {
       "expr": "collector_app_pegasus_app_stat_scan_qps{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "scan_qps"
      }
     ]
    },
    {
     "title": "集群读写吞吐量（统计最近10s内的读写吞吐量，单位：Capacity Unit）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collector_app_pegasus_app_stat_recent_read_cu{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "recent_read_cu"
      },
      {
       "expr": "collector_app_pegasus_app_stat_recent_write_cu{cluster=\"$cluster_name\", app=\"all\"}",
       "legendFormat": "recent_write_cu"
      }
     ]
    },
    {
     "title": "集群Partition健康状况（处于heathy、writable_ill、unwritable、unreadable、dead状态的partition个数）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "meta_eon_server_state_dead_partition_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "dead_partition_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_state_unreadable_partition_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "unreadable_partition_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_state_unwritable_partition_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "unwritable_partition_count@{{host_name}}@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_state_writable_ill_partition_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "writable_ill_partition_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_state_healthy_partition_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "healthy_partition_count@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 Get服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_GET_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 Get服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_GET_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 MultiGet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_GET_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 MultiGet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_GET_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 Set 服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_PUT_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 Set服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_PUT_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 MultiSet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_PUT_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 MultiSet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_PUT_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 Del服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_REMOVE_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 Del服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_REMOVE_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 MultiDel服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_REMOVE_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 MultiDel服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_MULTI_REMOVE_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 Incr服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_INCR_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 Incr服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_INCR_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 CheckAndSet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_CHECK_AND_SET_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 CheckAndSet服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_CHECK_AND_SET_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 CheckAndMutate服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_CHECK_AND_MUTATE_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 CheckAndMutate服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_CHECK_AND_MUTATE_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P99 Scan服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_SCAN_latency_server{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "P999 Scan服务端延迟（单位：纳秒）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zion_profiler_RPC_RRDB_RRDB_SCAN_latency_server_p999{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "集群Config更新情况（节点失联个数、config变化次数等）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "meta_eon_meta_service_recent_disconnect_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "disconnect_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_meta_service_unalive_nodes{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "unalive_nodes@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_state_recent_update_config_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "update_config_coun@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_state_recent_partition_change_unwritable_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "partition_change_unwritable_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_state_recent_partition_change_writable_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "partition_change_writable_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "meta_eon_server_load_balancer_recent_choose_primary_fail_count{cluster=\"$cluster_name\", pegasus_job=\"meta\"}",
       "legendFormat": "load_balancer_recent_choose_primary_fail_count@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点ReplicaServer异常统计（心跳失败次数、Prepare失败次数、Error文件夹个数、Garbage文件夹个数等）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_failure_detector_recent_beacon_fail_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "beacon_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_error_replica_dir_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "error_replica_dir_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_garbage_replica_dir_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "garbage_replica_dir_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_recent_prepare_fail_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "prepare_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_recent_replica_move_error_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "replica_move_error_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_recent_replica_move_garbage_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "replica_move_garbage_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_recent_replica_remove_dir_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "replica_remove_dir_count@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点Learning相关统计（执行次数、执行时间、传输数据量等）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_nfs_client_recent_copy_data_size{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "copy_data_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_nfs_client_recent_copy_fail_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "copy_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_nfs_client_recent_write_data_size{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "write_data_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_nfs_client_recent_write_fail_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "write_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_nfs_server_recent_copy_data_size{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "copy_data_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_nfs_server_recent_copy_fail_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "copy_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "learning_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_max_copy_file_size{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "max_copy_file_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_max_duration_time_ms_{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "max_duration_time@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_copy_buffer_size{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "copy_buffer_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_copy_file_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "copy_file_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_copy_file_size{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "copy_file_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_learn_app_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "learn_app_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_learn_cache_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "learn_cache_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_learn_fail_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "learn_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_learn_log_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "learn_log_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_learn_reset_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "learn_reset_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_learn_succ_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "learn_succ_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_round_start_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "round_start_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_replicas_learning_recent_start_count{cluster=\"$cluster_name\", pegasus_job=\"replica\"}",
       "legendFormat": "start_count@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点Cold-Backup相关统计（执行次数、执行时间、上传数据量等）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_eon_replica_stub_cold_backup_max_duration_time_ms{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "max_duration_time_ms@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_max_upload_file_size{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "max_upload_file_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_cancel_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "recent_cancel_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_fail_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_pause_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "recent_pause_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_start_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "start_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_succ_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "success_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_upload_file_fail_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "upload_file_fail_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_upload_file_size{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "upload_file_size@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_recent_upload_file_succ_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "upload_file_succ_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_eon_replica_stub_cold_backup_running_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "running_count@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点Manual-Compact相关统计（当前执行个数等）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_app_pegasus_manual_compact_running_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"pegasus\", mode=\"idle\"}[5m])) * 100)"
      }
     ]
    },
    {
     "title": "SSD Util",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total[5m]) * 100",
       "legendFormat": "{{device}}@{{instance}}"
      }
     ]
    },
    {
     "title": "各节点最近Flush写出字节数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_app_pegasus_recent_flush_output_bytes{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点最近Compaction写入写出字节数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_app_pegasus_recent_compaction_input_bytes{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "compaction_input_bytes@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_app_pegasus_recent_compaction_output_bytes{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "compaction_output_bytes@{{host_name}}:{{port}}"
      }
     ]
    },
    {
     "title": "各节点最近Write Stall触发次数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "replica_app_pegasus_recent_write_change_delayed_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "write_change_delayed_count@{{host_name}}:{{port}}"
      },
      {
       "expr": "replica_app_pegasus_recent_write_change_stopped_count{cluster='$cluster_name', pegasus_job='replica'}",
       "legendFormat": "write_change_stopped_count@{{host_name}}:{{port}}"
      }
     ]
    }
   ]
  }
 ]
}